name: CPP Build Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        testbranches: ['release','master']

    steps:
      - uses: actions/checkout@v2
      
      - name: Install DQ Robotics prerequisites
        run: | 
          git clone -b ${{ matrix.testbranches }} https://github.com/dqrobotics/cpp
          .\cpp\.github\scripts\windows\install_prerequisites.ps1

      - name: Install interface-coppeliasim-zmq prerequisites
        run: .\.github\scripts\windows\install_prerequisites.ps1

      - name: Build DQ Robotics
        run: |
          cd .\cpp\
          .\.github\scripts\windows\build.ps1

      - name: Install DQ Robotics
        run: |
          cd .\cpp\
          .\.github\scripts\windows\install.ps1
          
      - name: Build interface-coppeliasim-zmq 
        run: .\cpp\.github\scripts\windows\build.ps1
          
      - name: Install interface-coppeliasim-zmq 
        run: .\cpp\.github\scripts\windows\install.ps1
          

