name: CPP Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testbranches: ['release','master']

    steps:
      - uses: actions/checkout@v2

      - name: Apt update
        run: sudo apt update
        
      - name: Customize git
        run: |
          git submodule update --init --recursive
        
      - name: Install prerequisites
        run: |
          sudo apt install cmake g++ libeigen3-dev fakeroot
          
      - name: Build & install dqrobotics (${{ matrix.testbranches }})
        run: |
          git clone -b ${{ matrix.testbranches }} https://github.com/dqrobotics/cpp
          cd cpp
          sh .github/scripts/ubuntu/install_prerequisites.sh
          sh .github/scripts/ubuntu/build.sh
          sh .github/scripts/ubuntu/install.sh
          cd ..

      - name: Build & install cpp-interface-coppeliasim 
        run: |
          git clone -b main https://github.com/dqrobotics/cpp-interface-coppeliasim
          cd cpp-interface-coppeliasim
          chmod +x debian/rules
          fakeroot debian/rules clean
          fakeroot debian/rules build
          fakeroot debian/rules binary
          cd ..
          sudo apt install ./*.deb
          cd ..
          
      - name: Build & install cpp-interface-coppeliasim-zmq
        run: |
          sudo apt install libzmq3-dev libboost-all-dev
          git checkout
          mkdir -p build
          cd build
          cmake ..
          make
          cd ..
          chmod +x debian/rules
          fakeroot debian/rules clean
          fakeroot debian/rules build
          fakeroot debian/rules binary
          cd ..
          sudo apt install ./*.deb
          
